"""store canonical link on posts

Revision ID: 69438461c6e1
Revises: d05c460a4b44
Create Date: 2026-08-05 17:07:20.692546
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = '69438461c6e1'
down_revision: str | None = 'd05c460a4b44'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('posts', sa.Column('canonical_link', sa.String(length=1024), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('posts', 'canonical_link')
    # ### end Alembic commands ###
