"""post variants

Revision ID: d05c460a4b44
Revises: f9790093b021
Create Date: 2026-08-05 14:12:39.375912
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = 'd05c460a4b44'
down_revision: str | None = 'f9790093b021'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('post_variants',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('post_id', sa.Uuid(), nullable=False),
    sa.Column('angle', sa.String(length=64), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.Column('post_text', sa.Text(), nullable=True),
    sa.Column('first_comment_text', sa.Text(), nullable=True),
    sa.Column('intro_line', sa.Text(), nullable=True),
    sa.Column('hook_style', sa.String(length=64), nullable=True),
    sa.Column('origin', sa.String(length=16), nullable=False),
    sa.Column('model', sa.String(length=64), nullable=True),
    sa.Column('rejected', sa.JSON(), nullable=False),
    sa.Column('chosen_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['post_id'], ['posts.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('post_id', 'angle', name='uq_post_variants_angle')
    )
    op.create_index('ix_post_variants_post', 'post_variants', ['post_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_post_variants_post', table_name='post_variants')
    op.drop_table('post_variants')
    # ### end Alembic commands ###
