"""initial schema — the Phase 1 baseline (spec §5.2).

Every BrandCortex-owned table. The brand database is never migrated from here: we hold a read-only seam
into it, and any schema change on that side belongs to the brand's own migrations.

Autogenerated from the models, then adjusted in two places. `server_default` is `sa.func.now()` rather
than the literal the generator emitted, so it renders per dialect instead of pinning one. And
`posts.utm_campaign` is uniquely indexed on purpose: it is the join key between site analytics and a
post, so two posts sharing one campaign would silently merge their traffic. Better a write error at
draft time than attribution that is quietly wrong.

Revision ID: f9790093b021
Revises:
Create Date: 2026-08-05
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = 'f9790093b021'
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('brand_config',
    sa.Column('brand', sa.String(length=64), nullable=False),
    sa.Column('display_name', sa.String(length=128), nullable=False),
    sa.Column('timezone', sa.String(length=64), nullable=False),
    sa.Column('default_locale', sa.String(length=8), nullable=False),
    sa.Column('voice', sa.JSON(), nullable=False),
    sa.Column('intro_bank', sa.JSON(), nullable=False),
    sa.Column('hashtags', sa.JSON(), nullable=False),
    sa.Column('unit_labels', sa.JSON(), nullable=False),
    sa.Column('tag_targets', sa.JSON(), nullable=False),
    sa.Column('north_star', sa.JSON(), nullable=False),
    sa.Column('scheduling', sa.JSON(), nullable=False),
    sa.Column('settings', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False),
    sa.PrimaryKeyConstraint('brand')
    )
    op.create_table('channel_tokens',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('brand', sa.String(length=64), nullable=False),
    sa.Column('channel', sa.String(length=64), nullable=False),
    sa.Column('account_ref', sa.String(length=128), nullable=False),
    sa.Column('encrypted_token', sa.LargeBinary(), nullable=False),
    sa.Column('token_kind', sa.String(length=32), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('refreshed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('scopes', sa.JSON(), nullable=False),
    sa.Column('refresh_meta', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('brand', 'channel', 'account_ref', name='uq_channel_tokens_account')
    )
    op.create_table('experiments',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('brand', sa.String(length=64), nullable=False),
    sa.Column('lever', sa.String(length=128), nullable=False),
    sa.Column('hypothesis', sa.Text(), nullable=True),
    sa.Column('arms', sa.JSON(), nullable=False),
    sa.Column('allocation', sa.JSON(), nullable=False),
    sa.Column('results', sa.JSON(), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('concluded_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_experiments_brand_status', 'experiments', ['brand', 'status'], unique=False)
    op.create_table('intro_history',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('brand', sa.String(length=64), nullable=False),
    sa.Column('source_type', sa.String(length=64), nullable=True),
    sa.Column('locale', sa.String(length=8), nullable=True),
    sa.Column('intro_line', sa.Text(), nullable=False),
    sa.Column('used_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('post_id', sa.Uuid(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_intro_history_brand_used', 'intro_history', ['brand', 'used_at'], unique=False)
    op.create_table('playbook',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('brand', sa.String(length=64), nullable=False),
    sa.Column('rule_key', sa.String(length=128), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('rule', sa.Text(), nullable=False),
    sa.Column('payload', sa.JSON(), nullable=False),
    sa.Column('proposed_by', sa.String(length=64), nullable=True),
    sa.Column('evidence', sa.Text(), nullable=True),
    sa.Column('sample_size', sa.Integer(), nullable=False),
    sa.Column('confidence', sa.Numeric(precision=4, scale=3), nullable=True),
    sa.Column('verification', sa.JSON(), nullable=False),
    sa.Column('evidence_from', sa.DateTime(timezone=True), nullable=True),
    sa.Column('evidence_to', sa.DateTime(timezone=True), nullable=True),
    sa.Column('prediction', sa.JSON(), nullable=False),
    sa.Column('prediction_result', sa.JSON(), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('approved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('retired_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('brand', 'rule_key', 'version', name='uq_playbook_rule_version')
    )
    op.create_index('ix_playbook_brand_status', 'playbook', ['brand', 'status'], unique=False)
    op.create_table('posts',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('content_id', sa.String(length=64), nullable=False),
    sa.Column('brand', sa.String(length=64), nullable=False),
    sa.Column('channel', sa.String(length=64), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('asset_storage_key', sa.String(length=512), nullable=True),
    sa.Column('facts', sa.JSON(), nullable=False),
    sa.Column('post_text', sa.Text(), nullable=True),
    sa.Column('first_comment_text', sa.Text(), nullable=True),
    sa.Column('generated_post_text', sa.Text(), nullable=True),
    sa.Column('generated_first_comment_text', sa.Text(), nullable=True),
    sa.Column('utm_campaign', sa.String(length=128), nullable=True),
    sa.Column('source_generated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('scheduled_for', sa.DateTime(timezone=True), nullable=True),
    sa.Column('approved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('published_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('channel_post_id', sa.String(length=128), nullable=True),
    sa.Column('channel_comment_id', sa.String(length=128), nullable=True),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('content_id', 'channel', name='uq_posts_content_channel')
    )
    op.create_index(op.f('ix_posts_brand'), 'posts', ['brand'], unique=False)
    op.create_index('ix_posts_brand_status', 'posts', ['brand', 'status'], unique=False)
    op.create_index(op.f('ix_posts_channel_post_id'), 'posts', ['channel_post_id'], unique=False)
    op.create_index(op.f('ix_posts_content_id'), 'posts', ['content_id'], unique=False)
    op.create_index('ix_posts_scheduled_for', 'posts', ['scheduled_for'], unique=False)
    op.create_index(op.f('ix_posts_source_generated_at'), 'posts', ['source_generated_at'], unique=False)
    op.create_index(op.f('ix_posts_utm_campaign'), 'posts', ['utm_campaign'], unique=True)
    op.create_table('post_features',
    sa.Column('post_id', sa.Uuid(), nullable=False),
    sa.Column('source_type', sa.String(length=64), nullable=True),
    sa.Column('intro_line', sa.Text(), nullable=True),
    sa.Column('hook_style', sa.String(length=64), nullable=True),
    sa.Column('post_hour', sa.Integer(), nullable=True),
    sa.Column('post_weekday', sa.Integer(), nullable=True),
    sa.Column('locale', sa.String(length=8), nullable=True),
    sa.Column('caption_length', sa.Integer(), nullable=True),
    sa.Column('hashtag_set', sa.String(length=128), nullable=True),
    sa.Column('tagged_partner', sa.Boolean(), nullable=True),
    sa.Column('wow_factor', sa.Numeric(precision=4, scale=3), nullable=True),
    sa.Column('dimensions', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False),
    sa.ForeignKeyConstraint(['post_id'], ['posts.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('post_id')
    )
    op.create_index(op.f('ix_post_features_source_type'), 'post_features', ['source_type'], unique=False)
    op.create_table('post_insights',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('post_id', sa.Uuid(), nullable=False),
    sa.Column('captured_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('reach', sa.Integer(), nullable=True),
    sa.Column('impressions', sa.Integer(), nullable=True),
    sa.Column('reactions', sa.Integer(), nullable=True),
    sa.Column('comments', sa.Integer(), nullable=True),
    sa.Column('shares', sa.Integer(), nullable=True),
    sa.Column('saves', sa.Integer(), nullable=True),
    sa.Column('link_clicks', sa.Integer(), nullable=True),
    sa.Column('utm_sessions', sa.Integer(), nullable=True),
    sa.Column('raw', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False),
    sa.ForeignKeyConstraint(['post_id'], ['posts.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('post_id', 'captured_at', name='uq_post_insights_snapshot')
    )
    op.create_index('ix_post_insights_post_captured', 'post_insights', ['post_id', 'captured_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_post_insights_post_captured', table_name='post_insights')
    op.drop_table('post_insights')
    op.drop_index(op.f('ix_post_features_source_type'), table_name='post_features')
    op.drop_table('post_features')
    op.drop_index(op.f('ix_posts_utm_campaign'), table_name='posts')
    op.drop_index(op.f('ix_posts_source_generated_at'), table_name='posts')
    op.drop_index('ix_posts_scheduled_for', table_name='posts')
    op.drop_index(op.f('ix_posts_content_id'), table_name='posts')
    op.drop_index(op.f('ix_posts_channel_post_id'), table_name='posts')
    op.drop_index('ix_posts_brand_status', table_name='posts')
    op.drop_index(op.f('ix_posts_brand'), table_name='posts')
    op.drop_table('posts')
    op.drop_index('ix_playbook_brand_status', table_name='playbook')
    op.drop_table('playbook')
    op.drop_index('ix_intro_history_brand_used', table_name='intro_history')
    op.drop_table('intro_history')
    op.drop_index('ix_experiments_brand_status', table_name='experiments')
    op.drop_table('experiments')
    op.drop_table('channel_tokens')
    op.drop_table('brand_config')
    # ### end Alembic commands ###
